#!/bin/bash

set -e

SCRIPT_NAME=$(basename "$0")

if [[ "${1:0:2}" == "-h" ]]; then
	echo "Usage: [V=1] [VERSION=<version>] [board=<board>] ${SCRIPT_NAME} [<version>]"
	exit 1
fi

if [[ -n "${1}" ]]; then
	version="${1}"
else
	: ${version:="latest"}
fi

: ${board:="arm64-usr"}

# Helper scripts should be run from the same location as this script.
SCRIPT_ROOT=$(dirname "$(readlink -f "$0")")
. "${SCRIPT_ROOT}/common.sh" || exit 1

# Script must run inside the chroot
restart_in_chroot_if_needed "$@"

formats="
	-ami
	-ami_vmdk
	pxe
	iso
	openstack
	openstack_mini
	-qemu
	qemu_uefi
	-qemu_uefi_secure
	-rackspace
	-rackspace_onmetal
	-rackspace_vhd
	-vagrant
	-vagrant_parallels
	-vagrant_virtualbox
	-vagrant_vmware_fusion
	-virtualbox
	-vmware
	-vmware_ova
	-vmware_raw
	-vmware_insecure
	-parallels
	-xen
	-gce
	-brightbox
	-cloudstack
	-cloudstack_vhd
	-digitalocean
	-exoscale
	-azure
	-hyperv
	-niftycloud
	-cloudsigma
	packet
	-interoute
"

for f in ${formats}; do
	if [[ "${f:0:1}" == "-" ]]; then
		[[ -z ${V} ]] || echo "skipping ${f:1}"
		continue
	fi

	cmd="${SCRIPT_ROOT}/image_to_vm.sh --from=${SCRIPT_ROOT}/../build/images/${board}/${version} --board=${board} --prod_image --format=${f}"
	
	echo "building ${f}:"
	echo "${cmd}"
	eval "${cmd}"
	echo ""
done
